# Default values for k8s-kubectl
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

service:
  type: ClusterIP
  name: k8s-kubectl
  internalPort: 4040
  port: 80

replicas: 3

image:
  repository: "adacr.azurecr.io/utilities/k8s-kubectl"
  tag: "latest"
  pullPolicy: "Always"

resources:
  limits:
   cpu: 100m
   memory: 128Mi
  requests:
   cpu: 100m
   memory: 128Mi

nodeSelector:
  Role: Utility

pdb:
  minAvailable: 2

livenessProbe:
  enabled: true
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 5

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 2
