apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: "k8s-kubectl"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: "k8s-kubectl"
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: "k8s-kubectl"
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
